import type { Metadata } from "next";
import "./globals.css";
import createClient from "@/supabase/server";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.from("files").select();

  return (
    <html lang="en">
      <body className="antialiased">
        <Navigation files={data} />

        {children}
      </body>
    </html>
  );
}
