import type { Metadata } from "next";
import "./globals.css";
import createClient from "@/supabase/server";
import Navigation from "@/components/navigation";
import { Source_Sans_3, Source_Code_Pro } from "next/font/google";
import cn from "@/lib/cn";
import type { File } from "@/types/supabase";

const sourceSans = Source_Sans_3({ subsets: ["latin"], variable: "--font-source-sans" });
const sourceCode = Source_Code_Pro({ subsets: ["latin"], variable: "--font-source-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.from("files").select().returns<File[]>();

  return (
    <html lang="en">
      <body
        className={cn(
          sourceSans.variable,
          sourceCode.variable,
          "flex h-screen font-sans text-gray-600 antialiased",
        )}
      >
        <Navigation files={data} />

        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
